### ISSUE TITLE
Featured no Payload JSON

### ISSUE THREAD

**Issue by rudieros** [olxbr/crm-lead-integration#24]
Olá!
Minha equipe tem uma demanda de receber no payload do webhook um campo descrevendo se um anúncio foi passado como `Featured` no xml que foi processado em batch. Não é interessante, por exemplo, consultarmos nossa base de dados no momento que recebemos a notificação pois em nosso sistema o anúncio pode já não estar mais em destaque.
Existe alguma forma de fazer isso da forma como o JSON é hoje?
Caso não exista, seria algo que vocês colocariam no roadmap?
Muito obrigado!

**Comment by marcieltorres** [comment]
@rudieros opa, e aí tudo certo?

Então, hoje não temos essa informação no payload do lead que é enviado ao CRM.

```
{
  "leadOrigin": "VivaReal",
  "timestamp": "2017-10-23T15:50:30.619Z",
  "originLeadId": "59ee0fc6e4b043e1b2a6d863",
  "originListingId": "87027856",
  "clientListingId": "a40171",
  "name": "Nome Consumidor",
  "email": "nome.consumidor@email.com",
  "ddd": "11",
  "phone": "999999999",
  "phoneNumber": "11999999999",
  "message": "Olá, tenho interesse neste imóvel. Aguardo o contato. Obrigado."
}
```

Podemos avaliar sim se é possível incluir essa informação sobre o tipo do anúncio.

Mas por enquanto, o ideal seria que vocês implementassem essa regra aí do lado vocês :)

**Comment by rudieros** [comment]
@marcieltorres opa, muito obrigado pela resposta rápida!
Então, como pode demorar 8h pra processar o xml, quando a gente recebe a notificação pode ser que o anúncio já não esteja mais em destaque no nosso sistema, então não tem muito valor essa informação. Poderíamos estimar, enfim... achamos que não vale a pena tentar contornar.
Vamos ficar no aguardo então, podemos deixar essa issue aberta e vocês avisam aqui do progresso?
Valeu mesmo!

**Comment by luccakazan** [comment]
Oi @rudieros, beleza?
Você pode me explicar um pouco melhor a demanda?
Hoje o payload não leva nenhuma informação do anúncio além do "clientListingId", todas as informações de anúncio são baseadas no CRM do cliente. Dessa forma mantemos uma fonte única para os tipos de informação. Seria uma mudança muito grande no sistema e no conceito do payload de lead.
