### ISSUE TITLE
Dúvidas sobre a homologação e SECRET_KEY

### ISSUE THREAD

**Issue by andersonTrampusch** [olxbr/crm-lead-integration#27]
Olá, eu tenho uma dúvida sobre a homologação.Caso eu tenha um Enpoint com o id do anunciante ex:https://ID-DO-ANUNCIANTE.yourdomain.com.br/grupozap/lead eu tenho que enviar um e-mail contendo todos os Enpoints de cada anunciante ou enviar um e-mail para cada?. 

E o SECRET_KEY será de cada Enpoint?, 

Eu irei receber o SECRET_KEY como resposta ao e-mail ou eu tenho que requisitar separadamente após a homologação?

**Comment by marcieltorres** [comment]
@andersonTrampusch 

**Sobre a `SECRET_KEY`**:

- É apenas uma por software integrador;
- Você vai receber após a homologação;

**Sobre os enpoints**:

- Após a homologação, sempre que algum novo cliente entrar em seu CRM e desejar ativar a integração de leads, deverá ser feita a solicitação via nosso suporte padrão, então ao solicitar (vocês ou o cliente) devem informar o ID do anunciante que vocês estão utilizando para essa url personalizada.

Abraço.

**Comment by FazBi** [comment]
@marcieltorres , Gostaria de desenvolver um CRM bem simples, para que cada imobiliária pudesse responder rapidamente a seus clientes a respeito dos leads no anuncio dele. Como as imobiliárias costumam postar os anúncios no Vivareal, ZAP, Imovelweb entre outros portais, meu aplicativo centralizaria os leads, tornando fácil a resposta.
Mas fico preocupado com a escalabilidade, pois o cadastro de cada novo cliente no meu CRM eu teria que mandar um email de cadastro para vocês, é isso mesmo?

**Comment by marcieltorres** [comment]
@FazBi atualmente temos um processo manual para criar a integração softwareXanunciante, a homologação do seu software ocorre uma única vez, mas `infelizmente` a cada novo anunciante que for usar seu software, deverá ocorrer um cadastro manual do nosso lado, afinal precisamos ter certeza que o anunciante deve usar de fato o seu software.

Temos esse cadastro disponível também no [CanalPro](https://canalpro.grupozap.com/login) , onde o próprio anunciante consegue incluir a url para integração de leads.

Abraço.
