### ISSUE TITLE
Dúvida de Integração 

### ISSUE THREAD

**Issue by viewbrasil** [olxbr/crm-lead-integration#35]
Gostaria de sanar uma dúvida sobre o que acontece com aqueles imóveis que já estão publicados manualmente no portal, quando finalizada a integração do XML com os imóveis? Gostaria de saber se eles são inativados ou continuam em anúncio.

**Comment by marcieltorres** [comment]
@viewbrasil os possíveis cenários são:

### Anúncio Manual diferente do anúncio que está no XML
- Ambos anúncios ficarão disponíveis
- O anúncio criado via XML não poderá ser editado manualmente através do canal pro
- O anúncio criado manualmente poderá continuar sendo alterado pelo canal pro

### Anúncio Manual igual ao anúncio que está no XML
- O anúncio que está no XML vai apresentar erro de duplicidade no processamento e não será processado
- O anúncio criado manualmente poderá continuar sendo alterado pelo canal pro
- Para que o anúncio via XML suba, é necessário que o anúncio manual seja excluído 

**Importante**: Os anúncios criados de forma manual **não** são excluídos automaticamente ao rodar uma carga via XML, a exclusão de anúncio manual deve ser feita de forma manual através do canal pro.

### Regra para inativação dos anúncios
- Independente do anúncio ser cadastrado de forma manual ou através do XML, as regras para inativação vão seguir a grade contratada pelo anunciante, quando exceder essa grade os anúncios serão inativados automaticamente.

Muito obrigado pelo seu questionamento, vamos incluir essas observações em nossa documentação oficial https://developers.grupozap.com/.
