### ISSUE TITLE
Dúvidas sobre Portais

### ISSUE THREAD

**Issue by leotramanda** [olxbr/crm-lead-integration#39]
Bom dia, esta integração serve para todos os portais, ZAP e VIVA REAL? Ou cada portal teria um Endpoint separado?

**Comment by marcieltorres** [comment]
Fala @leotramanda  beleza?

Temos um campo no payload chamado `leadOrigin` https://developers.grupozap.com/leads/integration/#envio-dos-leads

Então essa informação vai variar entre `Zap | VivaReal | GrupoZap`.

E sobre os endpoints: https://developers.grupozap.com/leads/integration/#exemplos-de-endpoints-que-poderao-ser-utilizados

**Comment by leotramanda** [comment]
Como posso fazer a homologação de leads de um cliente? Pelo whats estou em contato faz dois dias e nenhum atendente sabe como funciona, estão até confundindo com carga de XML de imóveis que é enviada, por e-mail já tentei e não me responderam.

**Comment by marcieltorres** [comment]
https://developers.grupozap.com/leads/integration/#envio-dos-leads

![image](https://user-images.githubusercontent.com/3493966/119157684-d384fc00-ba2b-11eb-9e51-484b2fff64cb.png)

O `clientListingId` é o id do anúncio gerenciado pelo próprio anunciante, então ele pode ser inserido via carga XML (https://developers.grupozap.com/feeds/vrsync/elements/listing/#listing-id) ou de forma manual através do CanalPro.

**Comment by leotramanda** [comment]
> https://developers.grupozap.com/leads/integration/#envio-dos-leads
> 
> ![image](https://user-images.githubusercontent.com/3493966/119157684-d384fc00-ba2b-11eb-9e51-484b2fff64cb.png)
> 
> O `clientListingId` é o id do anúncio gerenciado pelo próprio anunciante, então ele pode ser inserido via carga XML (https://developers.grupozap.com/feeds/vrsync/elements/listing/#listing-id) ou de forma manual através do CanalPro.

Funcionou agora, está recebendo os leads, só que o cliente tem ZAP e VIVA REAL, ambos chegam com o campo leadOrigin como GrupoZap, assim não consigo separar de qual dos portais esta vindo o lead.

**Comment by marcieltorres** [comment]
Isso varia de acordo com o contrato do anunciante, anunciantes que tem contratos GrupoZap o CRM não vai saber a origem do lead, isso é uma regra interna.
