### ISSUE TITLE
Endpoint parou de receber leads

### ISSUE THREAD

**Issue by filiperq** [olxbr/crm-lead-integration#41]
Olá,

Nosso webhost teve problemas e ficamos um dia com o sistema fora do ar. Recebemos os e-mail do grupo zap informando sobre o erro na integração de leads (pois nosso sistema estava fora do ar).

Após o retorno do nosso sistema, os leads não estão mais chegando ao nosso endpoint. Ao testar o endpoint com o Postman, tudo funciona normalmente.

Há ainda alguma verificação que devemos fazer?

**Comment by marcieltorres** [comment]
@filiperq esse não é o canal para suporte.

Mas respondendo sua pergunta, a configuração deve ter sido inativada devido as tentativas de envio sem sucesso. Basta você solicitar a abertura de um chamado no nosso suporte explicando essa situação.

Abraço.

**Comment by filiperq** [comment]
Certo, como encontro o suporte?
O canal que utilizávamos pelo grupo zap não está mais disponível
