### ISSUE TITLE
Dúvidas sobre homologação e configuração pelos meus clientes

### ISSUE THREAD

**Issue by Fernando-Plantatica** [olxbr/crm-lead-integration#45]
Olá!
Já validei o endpoint de minha aplicação mas ainda tenho 2 dúvidas antes de enviar para homologação:
1) Estou adotando a opção da url 1 "https://yourdomain.com.br/grupozap/lead/ID-DO-ANUNCIANTE" e seria esta url que devo informar para homologação. Entretanto, cada cliente de meu CRM tem um ID-DO-ANUNCIANTE diferente em minha aplicação, o que me permite identificar para qual empreendimento o lead recebido deve ser direcionado. Entendo que a homologação valida o endpoint "https://yourdomain.com.br/grupozap/lead/", ou seja, não precisaremos passar pela homologação para cada cliente que decidir integrar meu CRM com o grupo ZAP, certo?
2) Poderia me passar informações de como cada anunciante no grupo ZAP configura em sua conta no grupo ZAP a ativação da integração?
Obrigado,

**Comment by marcieltorres** [comment]
@Fernando-Plantatica Acabei de respondei um email com essas dúvidas, mas vou responder aqui também para ajudar outras pessoas que possam passar ter essas mesmas dúvidas.

1. Sobre o formato da URL: Sim, nós vamos homologar apenas uma URL, seguindo seu exemplo você vai nos fornecer a url `https://yourdomain.com.br/grupozap/lead/123456`. E sim, vocês não precisam homologar para cada cliente, nós homologamos o CRM e não a integração de cada anunciante. 
2. O anunciante consegue fazer essa configuração de duas formas:
     -  Abrindo chamado no nosso suporte;
     - Configurando através do CanalPro:
        
![image](https://user-images.githubusercontent.com/3493966/122764967-6658c680-d276-11eb-999d-4c77e5ba70ad.png)



Lembrando os passos para homologação:

1. Leia nossa documentação: https://developers.grupozap.com/leads/integration/#envio-dos-leads
2. Valide seu endpoint: https://developers.grupozap.com/leads/endpoint-validator/
3. Nos envie as informações necessárias: https://developers.grupozap.com/leads/integration/#homologacao
4. Vamos fazer as verificações necessárias e retornar com uma [SECRET KEY](https://developers.grupozap.com/leads/integration/#validacao-de-seguranca-secret-key) para ambiente produtivo

**Comment by Fernando-Plantatica** [comment]
Obrigado Marciel pela explicação. Já esclareceu muito. Mas ainda fiquei com uma dúvida. Vou usar a url https://yourdomain.com.br/grupozap/lead/123456 para um cliente, que na minha aplicação tem o ID 123456. Quando outro cliente for integrar, terá outro ID, por exemplo, 7891011. Repare que a base da url é a mesma, só alterando o ID. Para este segundo cliente, mesmo tendo ID diferente do primeiro, não será necessário nova homologação do meu endpoint, certo?

**Comment by Mordekhayx** [comment]
Olá, estou com uma dúvida sobre os dados que são capturados via Webhook da Zapier para a minha plataforma de Gestão de Marketing do RD Station. 

Os dados estão vindo normalmente, mas no campo de mensagem, está vindo com dados repetidos do código como na imagem anexada. Como eu posso só receber a mensagem nesse caso e configurar no Zapier?

![WhatsApp Image 2021-06-24 at 14 44 20](https://user-images.githubusercontent.com/48386633/123309751-b0061300-d4fb-11eb-92e9-c2fc8fc8e5e4.jpeg)

**Comment by Mordekhayx** [comment]
Agora você me pegou. Eu entendi parcialmente a sua dúvida. Pode me explicar como é essa homologação. Não sou da área de programação, mas estou disposto a entender como funciona esse processo.
