### ISSUE TITLE
Dúvida integração XML no formato VRSync (Vivareal)

### ISSUE THREAD

**Issue by feliperodarte** [olxbr/crm-lead-integration#47]
Olá,

Na documentação não encontrei os atributos para informar "Nº de andares" e "Nº de torres".

E através do cadastro manual pelo Canal Pro é possível inserir essas informações.

É possível cadastrar esses atributos através da integração XML?

Obrigado!

**Comment by robsonoduarte** [comment]
@feliperodarte o `VRSync` não possuiu suporte para esses dois campos, já priorizamos aqui para adiciona-los

**Comment by robsonoduarte** [comment]
@feliperodarte adicionamos o suporte para esses dois campos, qualquer dúvida só chamar.

https://developers.grupozap.com/feeds/vrsync/elements/details/#floors
