### ISSUE TITLE
Retornar 404 para integração de leads não existente não impede novas requisições

### ISSUE THREAD

**Issue by marcallkz** [olxbr/crm-lead-integration#48]
Após um cliente cancelar ou desfazer a integração através do meu CRM, o que devo retornar em futuras chamadas de API?

Atualmente é dado uma resposta com o status http 404 porém não é o suficiente para impedir novas requisições.

**Comment by eduardomatoss** [comment]
Olá @marcallkz, tudo bem ??

Tivemos alguns problemas na desativação das integrações de leads em nosso sistema nos últimos dias. Já realizamos a correção e ao ter o retorno com o `statusCode=404` vamos realizar a desativação da integração conforme nossa documentação evitando novas requisições.

Desculpe pelo transtorno. Abraço.
